// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Outbox struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	ScheduledAt    time.Time
	Metadata       []byte
	Payload        []byte
	TimesAttempted int32
}

type ProcessedItem struct {
	ID            uuid.UUID
	ProcessedAt   time.Time
	ProcessedData string
}
