// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saga.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createSagaInstance = `-- name: CreateSagaInstance :one
INSERT INTO saga_instances (id, status, payload, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
RETURNING id, status, payload, created_at, updated_at
`

type CreateSagaInstanceParams struct {
	ID      uuid.UUID
	Status  string
	Payload []byte
}

func (q *Queries) CreateSagaInstance(ctx context.Context, arg CreateSagaInstanceParams) (SagaInstance, error) {
	row := q.db.QueryRow(ctx, createSagaInstance, arg.ID, arg.Status, arg.Payload)
	var i SagaInstance
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSagaStep = `-- name: CreateSagaStep :exec
INSERT INTO saga_steps (saga_id, step_name, status, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
`

type CreateSagaStepParams struct {
	SagaID   uuid.UUID
	StepName string
	Status   string
}

func (q *Queries) CreateSagaStep(ctx context.Context, arg CreateSagaStepParams) error {
	_, err := q.db.Exec(ctx, createSagaStep, arg.SagaID, arg.StepName, arg.Status)
	return err
}

const getSagaInstance = `-- name: GetSagaInstance :one
SELECT id, status, payload, created_at, updated_at FROM saga_instances WHERE id = $1
`

func (q *Queries) GetSagaInstance(ctx context.Context, id uuid.UUID) (SagaInstance, error) {
	row := q.db.QueryRow(ctx, getSagaInstance, id)
	var i SagaInstance
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionSagaInstanceStatus = `-- name: TransitionSagaInstanceStatus :one
UPDATE saga_instances
SET    status = $1, updated_at = now()
WHERE  id = $2 AND status = $3
RETURNING id
`

type TransitionSagaInstanceStatusParams struct {
	NewStatus     string
	ID            uuid.UUID
	CurrentStatus string
}

func (q *Queries) TransitionSagaInstanceStatus(ctx context.Context, arg TransitionSagaInstanceStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, transitionSagaInstanceStatus, arg.NewStatus, arg.ID, arg.CurrentStatus)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const transitionSagaStepStatus = `-- name: TransitionSagaStepStatus :one
UPDATE saga_steps
SET    status = $1, updated_at = now()
WHERE  saga_id = $2 AND step_name = $3 AND status = $4
RETURNING id
`

type TransitionSagaStepStatusParams struct {
	NewStatus     string
	SagaID        uuid.UUID
	StepName      string
	CurrentStatus string
}

func (q *Queries) TransitionSagaStepStatus(ctx context.Context, arg TransitionSagaStepStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, transitionSagaStepStatus,
		arg.NewStatus,
		arg.SagaID,
		arg.StepName,
		arg.CurrentStatus,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
