// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://github.com/samuel-poirier/go-pubsub-demo"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/samuel-poirier/go-pubsub-demo/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/hc": {
            "get": {
                "description": "Returns ok if healthy",
                "produces": [
                    "application/json"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/api/v1/items/processed": {
            "get": {
                "description": "Returns top 100 last processed items",
                "produces": [
                    "application/json"
                ],
                "summary": "Endpoint to get processed items",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Number of items to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_samuel-poirier_go-pubsub-demo_consumer_internal_repository.ProcessedItem"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/items/processed/count": {
            "get": {
                "description": "Returns count of all processed items",
                "produces": [
                    "application/json"
                ],
                "summary": "Endpoint to count processed items",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/api/v1/items/processed/{id}": {
            "get": {
                "description": "Returns the processed item found by id",
                "produces": [
                    "application/json"
                ],
                "summary": "Endpoint get one processed item by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the item",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_samuel-poirier_go-pubsub-demo_consumer_internal_repository.ProcessedItem"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_samuel-poirier_go-pubsub-demo_consumer_internal_repository.ProcessedItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "processedAt": {
                    "type": "string"
                },
                "processedData": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go PubSub Demo Consumer API",
	Description:      "Example consumer API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
